Loadsa pruning
Heegu-sama/Homm3BG pull request #103
Opened 2024-03-20 15:54 UTC by Heegu-sama

I removed many useless words/sentences/paragraphs. Also miscellaneous work such as spell checking, Capitalizing game terms, fiddling with page layouts.

This has created new gaps/empty space that should probably be filled with more graphics. I had to remove some of them out of the way previously and now during this. For instance the big vertical mummy isn't anywhere right now.

Combat's citadel section is currently missing its notice box about attacking walls because I couldn't think of where to place it back.

2024-03-21 08:28 UTC, Heegu-sama commented
@qwrtln do you have time to re-fill some of the new gaps with art? I can do it myself tomorrow at the earliest.

2024-03-21 09:11 UTC, qwrtln commented
> @qwrtln do you have time to re-fill some of the new gaps with art? I can do it myself tomorrow at the earliest.
Please do it tomorrow, I'll help you with issues.

2024-03-21 21:55 UTC, qwrtln commented on sections/units.tex
> +    \includegraphics[width=\linewidth]{\cards/units.png}
```suggestion
  \includegraphics[width=\linewidth]{\cards/units.png}
```

2024-03-22 22:49 UTC, qwrtln approved these changes
Fake, one of the pictures does not represent a unit available in the game 🤪

2024-03-22 23:05 UTC, qwrtln commented
Hold on, printable build is messed up now... I'll get back to it tomorrow.

![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/4cc56c16-484d-4931-a64f-a78927f8956d)

2024-03-22 23:06 UTC, qwrtln reviewed
Need to fix those autoscaling images

2024-03-22 23:06 UTC, qwrtln requested changes
Right, miss click

2024-03-23 07:11 UTC, qwrtln approved these changes
All fixed

2024-03-23 07:42 UTC, merged