Add Python script appending pages only to select hyperlinks
Heegu-sama/Homm3BG pull request #108
Opened 2024-03-23 18:26 UTC by qwrtln

2024-03-24 08:29 UTC, csagataj2 requested changes

2024-03-24 08:29 UTC, csagataj2 commented on .github/insert_printable_hyperlinks.py
> +SECTIONS_DIRECTORY = "sections"
Use Path instead of strings from the start
```suggestion
SECTIONS_DIRECTORY = pathlib.Path(__file__).parent.parent / "sections"
```

2024-03-24 08:29 UTC, csagataj2 commented on .github/insert_printable_hyperlinks.py
> +    return pathlib.Path(f"./{directory}").glob("*.tex")
There is no need for this
```suggestion
```

2024-03-24 08:29 UTC, csagataj2 commented on .github/insert_printable_hyperlinks.py
> +    return line
Add typehint and make it simpler
```suggestion
def _replace_line(line: str):
    for pattern in HYPERLINKS_TO_REPLACE:
        if re.search(f"hyperlink{{{pattern}", line):
            line = line.replace(f"hyperlink{{{pattern}", f"pagelink{{{pattern}")
    return line
```

2024-03-24 08:29 UTC, csagataj2 commented on .github/insert_printable_hyperlinks.py
> +def _parse_file(file):
Add typehint
```suggestion
def _parse_file(file: fileinput.FileInput[str]):
```

2024-03-24 08:29 UTC, csagataj2 commented on .github/insert_printable_hyperlinks.py
> +    for filename in _list_tex_files(directory):
Add typehint and move glob.
```suggestion
def update_files(directory: pathlib.Path):
    for filename in directory.glob("*.tex"):
```

2024-03-24 22:03 UTC, qwrtln commented
@csagataj2 All fixed, thank you for your suggestions 👌🏻

2024-03-25 20:30 UTC, csagataj2 approved these changes

2024-03-26 07:21 UTC, Heegu-sama approved these changes

2024-03-26 07:26 UTC, merged