[RU] adding RU support + introduction page
Heegu-sama/Homm3BG pull request #242
Opened 2024-04-24 19:05 UTC by ohgodnotagain

2024-04-24 21:37 UTC, DarthGandalf commented
Why did you need to close the previous PR?

2024-04-24 21:37 UTC, DarthGandalf approved these changes

2024-04-24 21:49 UTC, qwrtln requested changes
Please make the change suggested by @DarthGandalf in the previous PR regarding `\providecommand`. Also, add `ru` to README in line 76.

2024-04-24 22:24 UTC, DarthGandalf commented
What about 6bc51eb ?

2024-04-24 23:08 UTC, DarthGandalf commented
I'm playing with some fonts, does this or this look any better?

![изображение](https://github.com/Heegu-sama/Homm3BG/assets/325092/17361c0e-b67e-4ac5-b24e-03afc93d794d)
![изображение](https://github.com/Heegu-sama/Homm3BG/assets/325092/8741445b-0c97-4d11-af79-1ecb20d4080d)

I'd like first font for text, but second font for headers, but I can't find how to combine them in a single document

2024-04-25 00:14 UTC, DarthGandalf commented
That's possible by switching to TTF fonts using

```latex
\usepackage[TU]{fontenc}
\usepackage{fontspec}
\setmainfont{Arial}
\newfontfamily\titlefont{Comic Sans MS}
```
Then using \titlefont (or whatever name was chosen) in \addsection

2024-04-26 07:50 UTC, qwrtln commented on README.md
> +| 🇷🇺 Русский   |~1%|[🇫🇷📜](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/main_ru.pdf)|[🇷🇺🖨️](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/printable_ru.pdf)
```suggestion
| 🇷🇺 Русский   |~1%|[🇷🇺📜](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/main_ru.pdf)|[🇷🇺🖨️](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/printable_ru.pdf)|[n/a](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/components_list_ru/components_list_ru.pdf)|
```

2024-04-26 07:52 UTC, qwrtln requested changes
Please generate all the `ru.po` files, so that someone doesn't get confused on their PR.

2024-04-26 09:49 UTC, qwrtln commented on README.md
> +| 🇷🇺 Русский   |~5%|[🇫🇷📜](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/main_ru.pdf)|[🇷🇺🖨️](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/printable_ru.pdf)
```suggestion
| 🇷🇺 Русский   |~5%|[🇷🇺📜](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/main_ru.pdf)|[🇷🇺🖨️](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/ru/printable_ru.pdf)|[n/a](https://raw.githubusercontent.com/qwrtln/Homm3BG-build-artifacts/components_list_ru/components_list_ru.pdf)|
```
The flag! Suggestion had it too.

2024-04-26 09:50 UTC, qwrtln approved these changes

2024-04-26 13:43 UTC, Heegu-sama approved these changes

2024-04-26 13:47 UTC, merged