[RU] player turns
Heegu-sama/Homm3BG pull request #279
Opened 2024-04-27 09:15 UTC by ohgodnotagain

![output-10](https://github.com/Heegu-sama/Homm3BG/assets/47557135/37487aad-d55f-4d5e-89ed-f67bec04f78d)
![output-11](https://github.com/Heegu-sama/Homm3BG/assets/47557135/497c8de9-e3a2-46b0-a819-0105b107bf99)
![output-12](https://github.com/Heegu-sama/Homm3BG/assets/47557135/5ab50089-a1ff-40bc-9784-d2a6f13088c2)

2024-04-27 10:52 UTC, qwrtln commented
You know what, maybe let's merge the PR which fixes fonts first. Those titles are awful.

2024-04-28 07:34 UTC, DarthGandalf requested changes

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"  \\item выполните все указания из секции \"в начале вашего хода...\".\n"
```suggestion
"  \\item выполните все эффекты вида «в начале вашего хода...».\n"
```

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"После выполнения действия города, переверните соответствующий жетон на карте города неактивной стороной вверх.\n"
```suggestion
"После выполнения действия города, переверните соответствующий жетон на карте города лицом вниз.\n"
```

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"Вы не можете выполнить это действие еще раз до начала следующего раунда.\n"
```suggestion
"Вы не можете выполнить это действие ещё раз до начала следующего раунда.\n"
```

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"В свою очередь, получение положительной морали отменяет отрицательную мораль при ее наличии.\n"
```suggestion
"В свою очередь, получение положительной морали отменяет отрицательную мораль при её наличии.\n"
```

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"  Ее герои не могут получать или терять мораль.\n"
```suggestion
"  Некрополис ни при каких обстоятельствах не может получать или терять мораль.\n"
```

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"У неё есть 3 карты на руке с предыдущего раунда, и она решает сбросить 2 из них перед набором карт для своей колоды, солгасно её лимиту руки \\includesvg[height=10px]{\\svgs/hand.svg}.\n"
```suggestion
"У неё есть 3 карты на руке с предыдущего раунда, и она решает сбросить 2 из них перед набором карт для своей колоды, согласно её лимиту руки \\includesvg[height=10px]{\\svgs/hand.svg}.\n"
```

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"Так как уровеь её основного героя 3, то лимит равен 5, она набирает 4 карты после сброса (см. \\hyperlink{Level}{Уровни Эффектов}).}\\par\n"
```suggestion
"Так как уровень её основного героя 3, то лимит равен 5, она набирает 4 карты после сброса (см. \\hyperlink{Level}{Уровни Эффектов}).}\\par\n"
```

2024-04-28 07:34 UTC, DarthGandalf commented on translations/player_turns.tex/ru.po
> +"Так как Алиса объявляет намерение начать сражение, оба игрока все еще имеют возможность выполнить действия города.}\\par\n"
```suggestion
"Так как Алиса объявляет намерение начать сражение, оба игрока всё ещё имеют возможность выполнить действия города.}\\par\n"
```

2024-04-28 08:53 UTC, DarthGandalf approved these changes

2024-04-28 11:23 UTC, qwrtln approved these changes

2024-04-28 12:26 UTC, merged