[RU] heroes
Heegu-sama/Homm3BG pull request #283
Opened 2024-04-27 11:51 UTC by ohgodnotagain

![output-13](https://github.com/Heegu-sama/Homm3BG/assets/47557135/8a7805dd-05b5-485c-b0ba-d4f1255ef226)
![output-14](https://github.com/Heegu-sama/Homm3BG/assets/47557135/4d26bdbd-7fc7-4b3e-93e6-f2f62fed229f)
![output-15](https://github.com/Heegu-sama/Homm3BG/assets/47557135/96d56f50-7924-4ebe-b3e1-c163f24d4b43)

2024-04-27 12:58 UTC, DarthGandalf requested changes

2024-04-27 12:58 UTC, DarthGandalf commented on translations/heroes.tex/ru.po
> +"Термин “герой игрока” применим к обоим из них.\n"
```suggestion
"Термин «герой игрока» применим к обоим из них.\n"
```

2024-04-27 13:08 UTC, ohgodnotagain commented on translations/heroes.tex/ru.po
> +"        Когда кубик попадает в верхний ряд, герой получает уровень.\n"
пришлось урезать текст, чтобы влезло по верстке

2024-04-27 13:19 UTC, DarthGandalf commented on translations/heroes.tex/ru.po
> +"Основной герой всегда начинает сценарий с уровня 1\\index{Level} и может повышать его получая опыт \\includesvg[height=10px]{\\svgs/experience.svg}.\n"
```suggestion
"Основной герой всегда начинает сценарий с уровня 1\\index{Level} и может повышать его, получая опыт \\includesvg[height=10px]{\\svgs/experience.svg}.\n"
```

2024-04-27 13:19 UTC, DarthGandalf commented on translations/heroes.tex/ru.po
> +"Наиболее частыми источниками получения опыта являются \\hyperlink{Resources}{кубик сокровищ} \\includesvg[height=10px]{\\svgs/treasure.svg} и \\hyperlink{Combatexperience}{сражение}.\n"
```suggestion
"Наиболее частыми источниками получения опыта являются \\hyperlink{Resources}{кубик сокровищ} \\includesvg[height=10px]{\\svgs/treasure.svg} и \\hyperlink{Combatexperience}{сражения}.\n"
```

2024-04-27 17:27 UTC, DarthGandalf commented on translations/heroes.tex/ru.po
> +"После найма вторичного героя, поместите миниатюру в контролируемый город или посёлок.\n"
```suggestion
"После найма вторичного героя поместите миниатюру в контролируемый город или посёлок.\n"
```

2024-04-27 17:32 UTC, DarthGandalf approved these changes

2024-04-28 11:23 UTC, qwrtln approved these changes

2024-04-28 12:28 UTC, merged