[FR] trading
Heegu-sama/Homm3BG pull request #293
Opened 2024-04-27 16:30 UTC by Gastonia02

Adding image a bit later

2024-04-28 11:26 UTC, qwrtln requested changes
Please update to use the LaTeX table.

2024-04-28 14:35 UTC, qwrtln commented
Please update the image.

2024-04-29 14:52 UTC, Gastonia02 commented
![main_fr_2-39_page-0001](https://github.com/Heegu-sama/Homm3BG/assets/167482371/d62e7924-9f07-4252-9220-959d450b3332)

2024-04-29 15:36 UTC, qwrtln approved these changes

2024-04-29 16:06 UTC, merged