Use proper quotes
Heegu-sama/Homm3BG pull request #296
Opened 2024-04-27 18:27 UTC by DarthGandalf

2024-04-27 18:32 UTC, DarthGandalf commented
To translators: this is how quotes look in English typography, in your language it may be different. LaTeX has these shortcuts for English quotes.

![both-2](https://github.com/Heegu-sama/Homm3BG/assets/325092/920aa5f2-d86b-4831-a123-4047d4f7f760)
![both-6](https://github.com/Heegu-sama/Homm3BG/assets/325092/53a2d7b1-f747-472a-a312-89dcb15719a8)
![both-25](https://github.com/Heegu-sama/Homm3BG/assets/325092/e4dcea01-b8d1-4ea9-b2ae-fad901ce24af)

2024-04-28 08:42 UTC, qwrtln approved these changes

2024-04-30 20:47 UTC, qwrtln requested changes
Yeah, on second thought, please remove all the fuzzy stuff that got added as a result of this change. Translations shouldn't be affected by this change.

2024-04-30 21:16 UTC, qwrtln commented on metadata.tex
> +\author{Hermanni ``Heegu''{} Karppela}
```suggestion
\author{Hermanni ``Heegu'' Karppela}
```
This is not needed any more

2024-05-01 07:02 UTC, qwrtln approved these changes

2024-05-01 09:56 UTC, Heegu-sama approved these changes

2024-05-01 10:07 UTC, merged