[RU] resources
Heegu-sama/Homm3BG pull request #301
Opened 2024-04-27 21:13 UTC by ohgodnotagain

![output-20](https://github.com/Heegu-sama/Homm3BG/assets/47557135/0524167b-922d-4f41-b88b-685311c3caba)

2024-04-27 21:54 UTC, DarthGandalf requested changes

2024-04-27 21:54 UTC, DarthGandalf commented on translations/resources.tex/ru.po
> +"В ситуациях, когда добыча ресурсов игрока увеличивается или уменьшается, передвиньте соответствующий кубик на треке добычи ресурсов на новое место.\\par\n"
Может, на жёлобе? или на ползунке?

2024-04-27 21:54 UTC, DarthGandalf commented on translations/resources.tex/ru.po
> +"его условиями. Ресурсы также можно \\hyperlink{Trading}{купить или обменять}. "
```suggestion
"В начале каждого сценария игроки устанавливают количество добываемых ресурсов в соответствии с "
"условиями сценария. Ресурсы также можно \\hyperlink{Trading}{купить или обменять}. "
```

2024-04-28 09:09 UTC, DarthGandalf commented on translations/resources.tex/ru.po
> +"  \\footnotesize\\textcolor{darkcandyapplered}{\\textit{\\textbf{Золото \\phantom{Materials}}}}\n"
```suggestion
"  \\footnotesize\\textcolor{darkcandyapplered}{\\textit{\\textbf{Золото \\phantom{Materials} \phantom{Materials}}}}\n"
```

2024-04-29 20:28 UTC, DarthGandalf approved these changes

2024-04-30 14:19 UTC, qwrtln approved these changes

2024-04-30 17:28 UTC, merged