[RU] town
Heegu-sama/Homm3BG pull request #303
Opened 2024-04-27 22:19 UTC by ohgodnotagain

![ru-21](https://github.com/Heegu-sama/Homm3BG/assets/47557135/8f935b74-56fc-4032-acae-4ef80e6e4bb9)

2024-04-27 22:30 UTC, DarthGandalf requested changes

2024-04-27 22:30 UTC, DarthGandalf commented on translations/town.tex/ru.po
> +"\\hypertarget{Town}{Каждая}\\index{Town} Фракция имеет собственный город, расположенный в центре стартового элемента карты.\n"
```suggestion
"\\hypertarget{Town}{У каждой}\\index{Town} Фракции есть собственный город, расположенный в центре стартового элемента карты.\n"
```

2024-04-27 22:30 UTC, DarthGandalf commented on translations/town.tex/ru.po
> +"Грод является вашей самой важной локацией, так как многие сценарии \\hyperlink{End}{могут завершиться}, если его \\hyperlink{Categories}{захватит} вражеский герой.\\par\n"
```suggestion
"Город является вашей самой важной локацией, так как многие сценарии \\hyperlink{End}{могут завершиться}, если его \\hyperlink{Categories}{захватит} вражеский герой.\\par\n"
```

2024-04-27 22:30 UTC, DarthGandalf commented on translations/town.tex/ru.po
> +"  \\item \\textbf{Ратуша} – предоставляет ресурсы или уникальные для Фракции навыки.\n"
Уверен насчёт навыков в этом контексте? Не способности?

2024-04-27 22:30 UTC, DarthGandalf commented on translations/town.tex/ru.po
> +"В каждом раунд может быть построено \\textbf{только одно здание} с использованием жетона строительства\\index{Build Token}.\n"
```suggestion
"В каждом раунде может быть построено \\textbf{только одно здание} с использованием жетона строительства\\index{Build Token}.\n"
```

2024-04-27 22:30 UTC, DarthGandalf commented on translations/town.tex/ru.po
> +"Чтобы построить здание, оплатите его стоимость в ресурсах, переверните жетон строительства на неактивную сторону и поместите карточку нового здания в отведённый слот на карте города.\n"
```suggestion
"Чтобы построить здание, оплатите его стоимость в ресурсах, переверните жетон строительства лицом вниз и поместите карточку нового здания в отведённый ему слот на карте города.\n"
```

2024-04-27 22:30 UTC, DarthGandalf commented on translations/town.tex/ru.po
> +"Некоторые кароточки зданий имеют две стороны, и могут быть улучшены и перевёрнуты для отображения двух отдельных зданий одновременно. Такие улучшения должны \\textbf{происходить последовательно}.\\p
```suggestion
"Некоторые карточки зданий имеют две стороны и могут быть улучшены и перевёрнуты для отображения двух отдельных зданий одновременно. Такие улучшения должны \\textbf{происходить последовательно}.\\par\n"
```

2024-04-28 22:48 UTC, DarthGandalf approved these changes

2024-04-30 14:19 UTC, qwrtln approved these changes

2024-04-30 17:31 UTC, merged