Translation of page 25 - Units
Heegu-sama/Homm3BG pull request #315
Opened 2024-04-28 21:31 UTC by ArtOfTesting

2024-04-28 21:33 UTC, qwrtln commented
A czy tu nie ma tekstu, który już tłumaczyłeś?

2024-04-29 08:18 UTC, qwrtln commented on translations/units.tex/pl.po
> +=======
```suggestion
```

2024-04-29 16:03 UTC, evilmint commented on translations/units.tex/pl.po
> +"\"Garstka\" Po pokonaniu Jednostki są odrzucane z Walki i talii Jednostek ich właściciela.\n"
```suggestion
"\"Garstka\" Po pokonaniu Jednostki są odrzucane z Walki i Talii Jednostek ich właściciela.\n"
```

2024-04-29 16:05 UTC, evilmint commented on translations/units.tex/pl.po
> +"Jednostki zachowują swój status \"Garstka\" lub \"Grupa\" pomiędzy Walkami.\n"
```suggestion
"Jednostki zachowują swoją stronę \"Garstka\" lub \"Grupa\" pomiędzy Walkami.\n"
```

2024-04-29 16:08 UTC, evilmint commented on translations/units.tex/pl.po
> +"Na koniec Walki wszystkie obrażenia u wszystkich Jednostek są uleczone.\\par\n"
imo niefortunny dobór słów w angielskim tekście, leczenie sugeruje osobną mechanikę :(

2024-04-29 16:09 UTC, evilmint commented on translations/units.tex/pl.po
> +"\\includegraphics[height=30px]{\\images/initiative.png}{\\hypertarget{Initiative}{\\textbf{Inicjatywa}}} - Określa, kiedy Jednostka aktywuje się podczas walki.\n"
```suggestion
"\\includegraphics[height=30px]{\\images/initiative.png}{\\hypertarget{Initiative}{\\textbf{Inicjatywa}}} - Określa, kiedy Jednostka aktywuje się podczas Walki.\n"
```

2024-04-29 16:13 UTC, evilmint commented on translations/units.tex/pl.po
> +"    In case of multiple attacks, resolve the effect for \\textbf{the first attack only}.\n"
do przetłumaczenia

2024-04-29 16:13 UTC, evilmint commented on translations/units.tex/pl.po
> +"  \\item\\textbf{Kontratak} \\includesvg[height=10px]{\\svgs/unit_retaliate.svg} rozpatruje się, gdy jednostka kontratakuje.\n"
```suggestion
"  \\item\\textbf{Kontratak} \\includesvg[height=10px]{\\svgs/unit_retaliate.svg} rozpatruje się, gdy Jednostka kontratakuje.\n"
```

2024-04-29 16:17 UTC, evilmint commented on translations/units.tex/pl.po
> +"Kara ta jest również stosowana, jeśli \\includesvg[height=10px]{\\svgs/unit_ranged.svg} Jednostka atakuje z własnej Linii Tyłu na Tylną Linię wroga.\n"
może tak naturalniej?

```suggestion
"Kara ta jest również stosowana, jeśli Jednostka \\includesvg[height=10px]{\\svgs/unit_ranged.svg} atakuje z własnej Linii Tyłu na Tylną Linię wroga.\n"
```

2024-04-29 16:20 UTC, evilmint commented on translations/units.tex/pl.po
> +"Jeśli w Talii Jednostek Neutralnych kiedykolwiek skończą się Karty, przetasuj odrzucone karty w nową Talię.\n"
```suggestion
"Jeśli w Talii Jednostek Neutralnych skończą się Karty, przetasuj odrzucone karty w nową Talię.\n"
```

2024-04-29 16:20 UTC, evilmint commented on translations/units.tex/pl.po
> +"Każda z tych Talii powinna być zawsze oddzielona od siebie i tasowana podczas przygotowania.\n"
```suggestion
"Każda z tych Talii powinna być oddzielona od siebie i tasowana podczas przygotowania.\n"
```

2024-04-29 16:20 UTC, evilmint commented on translations/units.tex/pl.po
> +"Kiedy rozpocznie się Walka z Jednostkami Neutralnymi, wylosuj \\hyperlink{Difficulty}{odpowiednią liczbę} Jednostek z każdego poziomu, aby wziąć udział w tej Walce.\\par\n"
```suggestion
"Kiedy rozpocznie się Walka z Jednostkami Neutralnymi, wylosuj \\hyperlink{Difficulty}{odpowiednią liczbę} Jednostek każdego poziomu, aby wziąć udział w tej Walce.\\par\n"
```

2024-04-29 16:21 UTC, evilmint commented on translations/units.tex/pl.po
> +"Gracze mogą dodawać jednostki neutralne do swojej talii jednostek poprzez różne efekty, opisane w Zasadach Specyficznych dla Scenariusza lub Kartę Zdolności Dyplomacja.\n"
```suggestion
"Gracze mogą dodawać Jednostki Neutralne do swojej Talii Jednostek poprzez różne efekty, opisane w Zasadach Specyficznych dla Scenariusza lub Kartę Zdolności Dyplomacja.\n"
```

2024-04-29 16:23 UTC, evilmint commented on translations/units.tex/pl.po
> +"\\textit{Bob, grając jako Alamar Czarnoksiężnik, rzuca czar Magiczna Strzała na grupę Szkieletów Ali, Wzmacniając \\includesvg[height=10px]{\\svgs/empower.svg} Zaklęcie o 2 za pomocą Mistrzowskiego
```suggestion
"\\textit{Bob, grając jako Alamar Czarnoksiężnik, rzuca Zaklęcie ,,Magiczna Strzała'' na grupę Szkieletów Alicji, Wzmacniając \\includesvg[height=10px]{\\svgs/empower.svg} Zaklęcie o 2 za pomocą Efektu Mistrzowskiego \\includesvg[height=10px]{\\svgs/expert.svg} Karty Mocy.}\n"
```

2024-04-29 16:25 UTC, evilmint commented on translations/units.tex/pl.po
> +"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc są teraz zwrócone na stronę \"Garstka\" z 1 pozostałym obrażeniem \\includesvg[height=10px]{\\svgs/d
```suggestion
"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc zostają teraz odwrócone na stronę \"Garstka\" z 1 pozostałym obrażeniem \\includesvg[height=10px]{\\svgs/damage.svg} umieszczonym na nich.\n"
```

2024-04-30 12:56 UTC, ArtOfTesting commented on translations/units.tex/pl.po
> +"\\textit{Bob, grając jako Alamar Czarnoksiężnik, rzuca czar Magiczna Strzała na grupę Szkieletów Ali, Wzmacniając \\includesvg[height=10px]{\\svgs/empower.svg} Zaklęcie o 2 za pomocą Mistrzowskiego
Specjalnie dałem Ali, żeby było krócej, ale spoko :)

2024-04-30 13:05 UTC, ArtOfTesting commented on translations/units.tex/pl.po
> +"Na koniec Walki wszystkie obrażenia u wszystkich Jednostek są uleczone.\\par\n"
W swoim commicie uzyles takiego sformulowania
"Po Walce, przetrwałe Jednostki zostają wyleczone z Ran."
Użyję tego samego.

2024-04-30 13:06 UTC, ArtOfTesting commented on translations/units.tex/pl.po
> +"Na koniec Walki wszystkie obrażenia u wszystkich Jednostek są uleczone.\\par\n"
```suggestion
"Na koniec Walki, przetrwałe Jednostki zostają wyleczone z Ran.\\par\n"
```

2024-04-30 14:49 UTC, evilmint commented on translations/units.tex/pl.po
> +"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc zostają teraz odwrócone na stronę \"Garstka\" z 1 pozostałym obrażeniem \\includesvg[height=10px]{\\
```suggestion
"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc zostają teraz odwrócone na stronę ,,Garstka'' z 1 pozostałym obrażeniem \\includesvg[height=10px]{\\svgs/damage.svg} umieszczonym na nich.\n"
```

2024-04-30 14:50 UTC, evilmint commented on translations/units.tex/pl.po
> +"Jednostki zachowują swoją stronę \"Garstka\" lub \"Grupa\" pomiędzy Walkami.\n"
```suggestion
"Jednostki zachowują swoją stronę ,,Garstka'' lub ,,Grupa'' pomiędzy Walkami.\n"
```

2024-04-30 14:51 UTC, evilmint commented on translations/units.tex/pl.po
> +"\"Grupa\" Jednostki sa odwracane na stronę \"Garstka\", wszelkie dodatkowe obrażenia umieszczane są na stronie \"Garstka\".\n"
```suggestion
",,Grupa'' Jednostki są odwracane na stronę ,,Garstka'', wszelkie dodatkowe obrażenia umieszczane są na stronie ,,Garstka''.\n"
```

2024-04-30 14:51 UTC, evilmint commented on translations/units.tex/pl.po
> +"\"Garstka\" Po pokonaniu Jednostki są odrzucane z Walki i Talii Jednostek ich właściciela.\n"
```suggestion
",,Garstka'' Po pokonaniu Jednostki są odrzucane z Walki i Talii Jednostek ich właściciela.\n"
```

2024-04-30 17:02 UTC, evilmint approved these changes

2024-05-01 07:38 UTC, qwrtln requested changes
Za dużo tekstu. Zaraz się temu przyjrzymy.

2024-05-01 08:34 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\includegraphics[width=\\linewidth]{\\cards/units.png}\n"
```suggestion
"  \\includegraphics[width=\\linewidth]{translations/assets/pl/units.png}\n"
```

2024-05-01 08:36 UTC, qwrtln commented on translations/units.tex/pl.po
> +"    \\item[\\textbf{11.}]{Zdolność Specjalna}\n"
```suggestion
"    \\item[\\textbf{7.}] {Inicjatywa}\n"
"    \\item[\\textbf{8.}] {Koszt\\Rekrutowania}\n"
"    \\item[\\textbf{9.}] {Koszt\\Wzmocnienia}\n"
"    \\item[\\textbf{10.}]{Oznaczenie strony karty}\n"
"    \\item[\\textbf{11.}]{Zdolność\\Specjalna}\n"
```

2024-05-01 08:38 UTC, qwrtln commented on translations/units.tex/pl.po
> +",,Garstka'' Po pokonaniu Jednostki są odrzucane z Walki i Talii Jednostek ich właściciela.\n"
```suggestion
",,Garstka'' po pokonaniu jest odrzucana z Walki i Talii Jednostek ich właściciela.\n"
```

2024-05-01 08:40 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Jednostki zachowują swoją stronę ,,Garstka'' lub ,,Grupa'' pomiędzy Walkami.\n"
```suggestion
"Jednostki pozostają ,,Garstką'' lub ,,Grupą'' pomiędzy Walkami.\n"
```

2024-05-01 08:41 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Na koniec Walki, przetrwałe Jednostki zostają wyleczone z Ran.\\par\n"
```suggestion
"Na końcu Walki przetrwałe Jednostki są leczone z ran.\\par\n"
```

2024-05-01 08:55 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Większość Jednostek posiada \\textbf{zdolność specjalną}\\index{Zdolność Specjalna}:\\par\n"
```suggestion
"Większość Jednostek ma \\textbf{zdolność specjalną}\\index{Zdolność Specjalna}:\\par\n"
```

2024-05-01 08:57 UTC, qwrtln commented on translations/units.tex/pl.po
> +"    W przypadku wielu ataków, rozstrzygnij efekt tylko dla \\textbf{pierwszego ataku}."
```suggestion
"    W przypadku wielu ataków, rozstrzygnij efekt \\textbf{tylko dla pierwszego ataku}."
```

2024-05-01 08:59 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\item\\textbf{Bierna} \\includesvg[height=10px]{\\svgs/unit_passive.svg} rozpatruje się za każdym razem, gdy warunek jest spełniony.\n"
```suggestion
"  \\item\\textbf{Bierna} \\includesvg[height=10px]{\\svgs/unit_passive.svg} rozpatruje się za każdym razem, gdy spełniony jest dany warunek.\n"
```

2024-05-01 09:00 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\item W przypadku braku któregokolwiek z powyższych symboli, zdolność Jednostki jest używana zgodnie z jej tekstem.\n"
```suggestion
"  \\item W pozostałych przypadkach zdolność Jednostki jest używana zgodnie z jej tekstem.\n"
```

2024-05-01 09:01 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\item \\textbf{Naziemne}\\index{Jednostki Naziemne} \\includesvg[height=10px]{\\svgs/unit_ground.svg} Jednostki mogą poruszyć się o maksymalnie 3 pola, a następnie zaatakować sąsiadującą Jednostk
```suggestion
"  \\item \\textbf{Naziemne}\\index{Jednostki Naziemne} \\includesvg[height=10px]{\\svgs/unit_ground.svg} mogą poruszyć się o maksymalnie 3 pola, a następnie zaatakować sąsiadującą Jednostkę.\n"
```

2024-05-01 09:02 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\item \\textbf{Latające}\\index{Jednostki Latające} \\includesvg[height=10px]{\\svgs/unit_flying.svg} Jednostki mogą poruszyć się o maksymalnie 3 pola, \\textbf{ignorując Przeszkody Terenowe}, a
```suggestion
"  \\item \\textbf{Latające}\\index{Jednostki Latające} \\includesvg[height=10px]{\\svgs/unit_flying.svg} mogą poruszyć się o maksymalnie 3 pola, \\textbf{ignorując Przeszkody Terenowe}, a następnie zaatakować sąsiadującą Jednostkę.\n"
```

2024-05-01 09:02 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\item \\textbf{Strzelające}\\index{Jednostki Strzelające} \\includesvg[height=10px]{\\svgs/unit_ranged.svg} Jednostki mogą zaatakować \\textbf{dowolną wrogą Jednostkę}, a następnie poruszyć się o
```suggestion
"  \\item \\textbf{Strzelające}\\index{Jednostki Strzelające} \\includesvg[height=10px]{\\svgs/unit_ranged.svg} mogą zaatakować \\textbf{dowolną wrogą Jednostkę}, a następnie poruszyć się o maksymalnie 1 pole LUB poruszyć się o jedno pole bez ataku.\n"
```

2024-05-01 09:03 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\item \\textbf{Strzelające}\\index{Jednostki Strzelające} \\includesvg[height=10px]{\\svgs/unit_ranged.svg} Jednostki mogą zaatakować \\textbf{dowolną wrogą Jednostkę}, a następnie poruszyć się o
Zastanawiam się, czy te indeksy nie powinny brzmieć "Strzelające, Jednostki" zamiast "Jednostki Strzelające".

2024-05-01 09:06 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Atakując w ten sposób, \\includesvg[height=10px]{\\svgs/unit_ranged.svg} Jednostka otrzumuje karę do Walki, \\index{Kara do Walki}: rzuć dwiema Kośćmi Ataku (zamiast jednej) i \\textbf{rozpatrz mnie
```suggestion
"Atakując w ten sposób, Jednostka \\includesvg[height=10px]{\\svgs/unit_ranged.svg} otrzumuje karę do Walki\\index{Kara do Walki}: rzuć dwiema Kośćmi Ataku (zamiast jednej) i \\textbf{rozpatrz mniejszy wynik}.\\par\n"
```

2024-05-01 09:06 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Kara ta jest również stosowana, jeśli Jednostka \\includesvg[height=10px]{\\svgs/unit_ranged.svg} atakuje z własnej Linii Tyłu na Tylną Linię wroga.\n"
```suggestion
"Kara ta jest również stosowana, jeśli Jednostka \\includesvg[height=10px]{\\svgs/unit_ranged.svg} atakuje z własnej Drugiej Linii na Drugą Linię wroga.\n"
```

2024-05-01 09:07 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Każda z tych Talii powinna być oddzielona od siebie i tasowana podczas przygotowania.\n"
```suggestion
"Każda z tych Talii powinna być oddzielona od siebie i potasowana podczas przygotowania.\n"
```

2024-05-01 09:10 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Gracze mogą dodawać Jednostki Neutralne do swojej Talii Jednostek poprzez różne efekty, opisane w Zasadach Specyficznych dla Scenariusza lub poprzez Kartę Zdolności Dyplomacja.\n"
```suggestion
"Gracze mogą dodawać Jednostki Neutralne do swojej Talii Jednostek poprzez różne efekty opisane w Zasadach Specyficznych dla Scenariusza lub dzięki Karcie Zdolności Dyplomacji.\n"
```

2024-05-01 09:11 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Za każdym razem, gdy jednostka neutralna zostanie pokonana, umieść ją na odpowiednim Stosie Neutralnych Kart Odrzuconych.\\par\n"
```suggestion
"Gdy Jednostka Neutralna zostanie pokonana, umieść ją na odpowiednim Stosie Neutralnych Kart Odrzuconych.\\par\n"
```

2024-05-01 09:13 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc zostają teraz odwrócone na stronę ,,Garstka'' z 1 pozostałym obrażeniem \\includesvg[height=10px]{\\
```suggestion
"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc zostają teraz odwrócone na stronę ,,Garstki'' z 1 pozostałym punktem obrażeń \\includesvg[height=10px]{\\svgs/damage.svg} umieszczonym na nich.\n"
```

2024-05-01 21:44 UTC, ArtOfTesting commented on translations/units.tex/pl.po
> +"  \\item \\textbf{Strzelające}\\index{Jednostki Strzelające} \\includesvg[height=10px]{\\svgs/unit_ranged.svg} Jednostki mogą zaatakować \\textbf{dowolną wrogą Jednostkę}, a następnie poruszyć się o
nie nie, tak jest dobrze

2024-05-01 21:46 UTC, ArtOfTesting commented on translations/units.tex/pl.po
> +"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc zostają teraz odwrócone na stronę ,,Garstka'' z 1 pozostałym obrażeniem \\includesvg[height=10px]{\\
chciałem zachować nazwę własną 'Garstka' i nie odmieniac jej, przemyśl jeszcze raz

2024-05-02 06:44 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  \\item \\textbf{Strzelające}\\index{Jednostki Strzelające} \\includesvg[height=10px]{\\svgs/unit_ranged.svg} Jednostki mogą zaatakować \\textbf{dowolną wrogą Jednostkę}, a następnie poruszyć się o
No ale "strzelaczy" czy "lataczy" szukasz w indeksie pod J?

2024-05-02 06:54 UTC, qwrtln requested changes
Lepiej, ale jeszcze jest odrobinę za dużo.

2024-05-02 06:54 UTC, qwrtln commented
Z tabelką trzeba coś zrobić
![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/285da6ea-6b2e-4202-8b81-1e87eef48946)

2024-05-02 07:11 UTC, qwrtln commented on translations/units.tex/pl.po
> +"{Rycerze Grozy, Upiorne Smoki} \\\\ \\end{tabularx} }"
```suggestion
"\\hommtable{14}{ \\begin{tabularx}{\\linewidth}{XXXXX} \\darkcell{Jednostki} "
"& \\darkcell{Budynek } & \\darkcell{\\phantom{j}Zamek\\phantom{j}} & "
"\\darkcell{Lochy} & \\darkcell{Nekropolia} \\\\ \\darkcell[1.6]"
"{\\includesvg[height=12px]{\\svgs/bronze-table.svg} \\\\ Brązowe} & "
"\\lightcell[1.6]{Siedlisko \\\\ Poziomu 1} & \\lightcell[1.6]{Halabardnicy,\\"
"\\Kusznicy,\\\\Gryfy} & \\lightcell[1.6]{Troglodyci,\\\\Harpie,\\\\Złe Oczy} "
"& \\lightcell[1.6]{Szkielety,\\\\Zombie,\\\\Upiory} \\\\ \\darkcell[1.2]"
"{\\includesvg[height=12px]{\\svgs/silver.svg} \\\\ Srebrne} & "
"\\lightcell[1.2]{Siedlisko \\\\ Poziomu 2} & \\lightcell[1.2]{Krzyżowcy, "
"Kapłani} & \\lightcell[1.2]{Meduzy, Minotaury} & \\lightcell[1.2]{Wampiry,\\"
"\\ Licze} \\\\ \\darkcell[1.2]{\\includesvg[height=12px]{\\svgs/golden.svg} "
"\\\\ Złote} & \\lightcell[1.2]{Siedlisko \\\\ Poziomu 3} & \\lightcell[1.2]"
"{Czempioni, Archanioły} & \\lightcell[1.2]{Mantykory, Czarne Smoki} & "
"\\lightcell[1.2]{Rycerze Grozy, Upiorne Smoki} \\\\ \\end{tabularx} }"
```
![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/e0a3df72-382b-49df-8de7-82eca87226c4)

2024-05-02 07:26 UTC, qwrtln commented on translations/units.tex/pl.po
> +"Kara ta jest również stosowana, jeśli Jednostka \\includesvg[height=10px]{\\svgs/unit_ranged.svg} atakuje z własnej Drugiej Linii na Drugą Linię wroga.\n"
```suggestion
"Karę również stosuje się, jeśli Jednostka \\includesvg[height=10px]{\\svgs/unit_ranged.svg} atakuje z własnej Drugiej Linii na Drugą Linię wroga.\n"
```
To wystarczy, aby dokument zachował odpowiednią długość.

2024-05-02 07:32 UTC, qwrtln approved these changes

2024-05-02 07:32 UTC, merged

2024-05-02 07:35 UTC, qwrtln commented on translations/units.tex/pl.po
> +"  Szkielety mają tylko 2 Punkty Zdrowia \\includesvg[height=10px]{\\svgs/health_points.svg}, więc zostają teraz odwrócone na stronę ,,Garstka'' z 1 pozostałym obrażeniem \\includesvg[height=10px]{\\
Nazwa własna czy nie, "Garstka" jest rzeczownikiem i się deklinuje. Wszędzie indziej tak z nią robimy.