[RU] units
Heegu-sama/Homm3BG pull request #338
Opened 2024-04-30 20:51 UTC by ohgodnotagain

![ru-4](https://github.com/Heegu-sama/Homm3BG/assets/47557135/b72606ec-e5b9-4c7e-ac7c-1a8ca854fecc)
![ru-5](https://github.com/Heegu-sama/Homm3BG/assets/47557135/c6125d52-584b-4677-86a5-81f0aacd63f6)
![ru-6](https://github.com/Heegu-sama/Homm3BG/assets/47557135/a88769f4-0350-4b5d-b151-a66fa3297b81)
![ru-7](https://github.com/Heegu-sama/Homm3BG/assets/47557135/458d169d-1518-48ac-b0e0-32f693aeb020)

2024-04-30 21:51 UTC, DarthGandalf requested changes

2024-04-30 21:51 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"Если отряд несет поражение в битве, \\textbf{сбросьте его} из колоды.\\par\n"
```suggestion
"Если отряд несёт поражение в битве, \\textbf{сбросьте его} из колоды.\\par\n"
```

2024-04-30 21:51 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"\\textbf{Улучшение} требует возведенной Цитадели в дополнение к Жилищу соответствующего уровня.\\par\n"
```suggestion
"\\textbf{Найм} отрядов требует возведённого Жилища с уровнем отряда (\\includesvg[height=10px]{\\svgs/bronze.svg}\\includesvg[height=10px]{\\svgs/silver.svg}\\includesvg[height=10px]{\\svgs/golden.svg}).\n"
"\\textbf{Улучшение} требует возведённой Цитадели в дополнение к Жилищу соответствующего уровня.\\par\n"
```

2024-04-30 21:51 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"{\\svgs/silver.svg} \\\\ отряды} & \\lightcell[1.2]{Жилища \\\\ "
```suggestion
"{\\svgs/silver.svg} \\\\ отряды} & \\lightcell[1.2]{Жилище \\\\ "
```

2024-04-30 21:51 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"{Скелеты, Зомби, Духи} \\\\ \\darkcell[1.2]{\\includesvg[height=12px]"
```suggestion
"{Скелеты, Зомби,\\\\ Духи} \\\\ \\darkcell[1.2]{\\includesvg[height=12px]"
```

2024-04-30 21:51 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"\\textit{Боб, играющий за чернокнижника Аламара, колдует Волшебную стрелу против «pack» скелетов Алисы, усиляя \\includesvg[height=10px]{\\svgs/empower.svg} заклинание на 2 с экспертным эффектом \\i
```suggestion
"\\textit{Боб, играющий за чернокнижника Аламара, колдует Волшебную стрелу против «pack» скелетов Алисы, усиляя \\includesvg[height=10px]{\\svgs/empower.svg} заклинание на 2 с помощью экспертного эффекта \\includesvg[height=10px]{\\svgs/expert.svg} карты Силы магии.}\n"
```

Или «используя»

2024-05-04 11:50 UTC, qwrtln commented
Hi, please update again. You can now run po4a directly on GitHub. Just write "po4a check" comment.

2024-05-05 18:17 UTC, qwrtln approved these changes

2024-05-05 20:59 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"Отряды можно нанимать\\index{Recruiting} \\includesvg[height=10px]{\\svgs/pay.svg} и улучшать\\index{Reinforcing} \\includesvg[height=10px]{\\svgs/reinforce.svg}, оплатив цену операции и перевернув
```suggestion
"Отряды можно нанимать\\index{Recruiting} \\includesvg[height=10px]{\\svgs/pay.svg} и улучшать\\index{Reinforcing} \\includesvg[height=10px]{\\svgs/reinforce.svg}, оплатив цену операции и перевернув токен популяции лицом вниз.\n"
```

2024-05-05 20:59 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"    В случае нескольких атак, эффект применяется \\textbf{только для первой атаки}.\n"
```suggestion
"    В случае нескольких атак эффект применяется \\textbf{только для первой атаки}.\n"
```

2024-05-05 20:59 UTC, DarthGandalf commented on translations/units.tex/ru.po
> +"    Отряды также могут использовать символы \\hyperlink{Playerdecks}{усиления}.\n"
что ещё за усиление?

2024-05-06 14:51 UTC, DarthGandalf approved these changes

2024-05-06 18:33 UTC, merged