Introduction
Heegu-sama/Homm3BG pull request #356
Opened 2024-05-02 18:06 UTC by csagataj2

2024-05-02 18:34 UTC, qwrtln commented
Please attach screenshots of the translated pages.

2024-05-02 18:34 UTC, qwrtln commented
You can use the pdf2image.sh script in the repo

2024-05-03 06:21 UTC, qwrtln requested changes
Please fix the frame

2024-05-03 08:51 UTC, qwrtln commented on translations/introduction.tex/ua.po
> +"  \\includesvg[height=0.1px]{\\svgs/bronze-table.svg}\n"
```suggestion
```
This one's going to disappear.

2024-05-04 11:12 UTC, qwrtln commented
po4a check

2024-05-05 06:50 UTC, csagataj2 commented
po4a commit

2024-05-05 08:56 UTC, qwrtln commented on translations/introduction.tex/ua.po
> +"\\note{11}{Винятки та примітки з \\hyperlink{Heroes of Might and Magic III}{гіперпосиланнями} пояснюються у вікнах подібних до цього.\n"
```suggestion
"\\note{10}{\\vspace{1em}Винятки та примітки з \\hyperlink{Heroes of Might and Magic III}{гіперпосиланнями} пояснюються у вікнах подібних до цього.\n"
```

2024-05-05 09:26 UTC, qwrtln commented on translations/introduction.tex/ua.po
> +"\\note{11}{Винятки та примітки з \\hyperlink{Heroes of Might and Magic III}{гіперпосиланнями} пояснюються у вікнах подібних до цього.\n"
This is how it looks like with the change:
![ua-04](https://github.com/Heegu-sama/Homm3BG/assets/5611195/3fc2cdbf-b137-4f67-b594-e1c7e7a81778)

2024-05-05 09:31 UTC, qwrtln commented on translations/introduction.tex/ua.po
> +"\\note{11}{Винятки та примітки з \\hyperlink{Heroes of Might and Magic III}{гіперпосиланнями} пояснюються у вікнах подібних до цього.\n"
This is how it looks like with the change:

![ua-04](https://github.com/Heegu-sama/Homm3BG/assets/5611195/c85a87c7-c02c-4fb5-bbbb-5a7ce0ebb532)

2024-05-05 13:03 UTC, qwrtln commented on translations/introduction.tex/ua.po
> +"\\note{10}{\\vspace{1em}Винятки та примітки з \\hyperlink{Heroes of Might and Magic III}{гіперпосиланнями} пояснюються у вікнах подібних до цього.\n"
```suggestion
"\\note{10}{Винятки та примітки з \\hyperlink{Heroes of Might and Magic III}{гіперпосиланнями} пояснюються у вікнах подібних до цього.\n"
```
No longer necessary.

2024-05-05 13:10 UTC, qwrtln approved these changes

2024-05-05 13:11 UTC, merged