Ru/combat
Heegu-sama/Homm3BG pull request #409
Opened 2024-05-07 11:41 UTC by ohgodnotagain

**PLEASE IGNORE THE "END OF COMBAT" PART**

![ru-4](https://github.com/Heegu-sama/Homm3BG/assets/47557135/8db3a828-838d-45a1-8f19-7486efa7a4b5)
![ru-5](https://github.com/Heegu-sama/Homm3BG/assets/47557135/8d31df81-868f-4455-bb35-a33d49f462ce)
![ru-6](https://github.com/Heegu-sama/Homm3BG/assets/47557135/4e3e26b4-adc2-41cf-a10c-9b2f49c1fffc)
![ru-7](https://github.com/Heegu-sama/Homm3BG/assets/47557135/f5fe351c-5368-456d-8780-ede9c913ea7e)
![ru-8](https://github.com/Heegu-sama/Homm3BG/assets/47557135/859bb8b2-8fc5-49e8-b844-ac23180a9ef7)
![ru-9](https://github.com/Heegu-sama/Homm3BG/assets/47557135/35c0e745-6bcc-45fa-98ba-bf17cbd3759d)

2024-05-08 00:19 UTC, DarthGandalf requested changes

2024-05-08 00:19 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Если вы не можете выиграть сражение до конца текущего раунда, вы должны либо \\hyperlink{Endcombat}{отступить}\\index{Retreat}, либо использовать 1 ОП героя начавшего сражение для получения дополнит
```suggestion
"Если вы не можете выиграть сражение до конца текущего раунда, вы должны либо \\hyperlink{Endcombat}{отступить}\\index{Retreat}, либо использовать 1 ОП героя, начавшего сражение, для получения дополнительного раунда.\\par\n"
```

2024-05-08 00:19 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"\\note{5}{Сражения против Лазурных \\includesvg[height=10px]{\\svgs/azure-note.svg} отрядов, других игроков или \\hyperlink{AIrules}{ИИ героев} не имеют лимитов по раундам.}\n"
```suggestion
"\\note{5}{Сражения против Лазурных \\includesvg[height=10px]{\\svgs/azure-note.svg} отрядов, других игроков и \\hyperlink{AIrules}{ИИ героев} не имеют лимитов по раундам.}\n"
```

2024-05-08 00:19 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"  \\item При атаке смежным отрящом обороняющийся \\hyperlink{Retaliate}{контратакует}, если еще не делал этого в текущем раунде.\n"
```suggestion
"  \\item При атаке смежным отрядом обороняющийся \\hyperlink{Retaliate}{контратакует}, если ещё не делал этого в текущем раунде.\n"
```

Но всё равно звучит как-то криво.

Может, так? Если атакующий и обороняющийся отряды смежны, обороняющийся контр....

2024-05-08 00:19 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Если вы получили несколько уровней за раз, примените все эффекты от них.\n"
```suggestion
"Если вы получили несколько уровней за раз, примените все эффекты от них по порядку.\n"
```

2024-05-10 15:31 UTC, ohgodnotagain commented on translations/combat.tex/ru.po
> +"\\textbf{\\hypertarget{Retaliate}{Контрудар}} — если отряд выживает после атаки смежного отряда, он наносит контрудар атаковавшему противнику.\n"
закину тудушку на замену в юнитах
к тому же контрудар встречается в русской локализации игры (заклинание)

2024-06-03 20:17 UTC, DarthGandalf requested changes

2024-06-03 20:17 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"  \\item Перед атакой оба игрока могут \\hyperlink{CombatCards}{сыграть карты}. Игроки принимают решение, в каком порядке играются эти карты.\n"
в оригинале совсем не то

2024-06-03 20:17 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Если вы \\hyperlink{Timelimit}{не успели уничтожить противника за один ход} в сражении против \\textbf{нейтральных отрядов} или потеряли все свои отряды, вы должны \\textbf{отступить}; поместите выж
это не совсем так, там ещё можно тратить ОП для продолжения битвы, но это описано по ссылке

2024-06-03 20:17 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Если вторичный герой подвергается атаке, то вместо сражения он может \\textbf{сдаться} для сохранения отрядов.\n"
слово сдаться здесь не к месту, т.к. платить 10 голды не надо

2024-06-03 20:17 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Считается, что герой одержал победу над нейтральными отрядами, и вы не получаете наград.\n"
потерял предложение

2024-06-03 20:17 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Так как Боб объявил атаку, оба игрока имеют возможность изменить атаку и защиту своих отрядов, сыграв любое количество \\includesvg[height=10px]{\\svgs/instant.svg} карт, увеличивающих \\includesvg[
```suggestion
"Когда Боб объявил атаку, оба игрока имеют возможность изменить атаку и защиту своих отрядов, сыграв любое количество \\includesvg[height=10px]{\\svgs/instant.svg} карт, увеличивающих \\includesvg[height=10px]{\\svgs/attack.svg} атакующих отрядов или \\includesvg[height=10px]{\\svgs/defense.svg} обороняющихся.}\\par\n"
```

2024-06-09 05:49 UTC, Minifets commented on translations/combat.tex/ru.po
> +"  \\item при попадании на поле с замком или посёлком, которыми они владеют.\n"
В данном случае он, т.к. в контексте это другой игрок.
Тут работает правило, что слово игрок мужского рода, поэтому используется местоимение он.

2024-06-10 12:50 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Если вы \\hyperlink{Timelimit}{не успели уничтожить противника за один ход} в сражении против \\textbf{нейтральных отрядов} или потеряли все свои отряды, вы должны \\textbf{отступить}; поместите выж
что-то поменялось?

2024-06-18 15:03 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"Если вы \\hyperlink{Timelimit}{не успели уничтожить противника за один ход} в сражении против \\textbf{нейтральных отрядов} или потеряли все свои отряды, вы должны \\textbf{отступить}; поместите выж
собственно, и я о том же - конкретного числа ходов и что с этим делать нет в оригинале - только ссылка. И в переводе предлагаю также, как раз лучше влезать должно

Что-то типа `Если вы \\hyperlink{Timelimit}{не успели уничтожить противника} в сражении против`, а конкретное число ходов, ОП и лазурные - объяснены по ссылке

2024-06-18 15:16 UTC, DarthGandalf approved these changes

2024-06-18 15:58 UTC, qwrtln approved these changes

2024-06-19 06:10 UTC, merged