Improve printable index
Heegu-sama/Homm3BG pull request #469
Opened 2024-05-13 22:00 UTC by DarthGandalf

2024-05-14 07:31 UTC, qwrtln requested changes
Doesn't work in the workflow.

2024-05-14 07:33 UTC, qwrtln commented
This is the index page from the PDF built in the workflow:

![en-55](https://github.com/Heegu-sama/Homm3BG/assets/5611195/a4bbe4f6-6508-4921-a511-e1abc9b66903)

2024-05-14 08:04 UTC, qwrtln commented on .github/workflows/build-and-publish-rule-book.yaml
> +          pre_compile: export HOMM3_PRINTABLE=1 HOMM3_LANG=${{ matrix.language }}
```suggestion
        uses: xu-cheng/latex-action@v3
        env:
          HOMM3_PRINTABLE: 1
          HOMM3_LANG: ${{ matrix.language }}
        with:
          extra_system_packages: "inkscape"
```

2024-05-14 08:04 UTC, qwrtln commented on .github/workflows/build-and-publish-rule-book.yaml
> +          pre_compile: export HOMM3_PRINTABLE=1 HOMM3_LANG=${{ matrix.language }}
Not sure if it works on actions, though

2024-05-14 08:47 UTC, qwrtln commented on .github/workflows/build-and-publish-rule-book.yaml
> +          pre_compile: export HOMM3_PRINTABLE=1 HOMM3_LANG=${{ matrix.language }}
If that doesn't work, I guess you can just do 
```
echo "HOMM3_PRINTABLE=1" >> $GITHUB_ENV
```
in a previous step.

2024-05-14 21:19 UTC, DarthGandalf commented
Fixed the empty index.

Caveat: I simply took the first character, and compared their codepoints, ignoring existence of collation, so for some languages the result may be wrong. This will be easier to fix when such cases appear

2024-05-15 08:41 UTC, qwrtln commented
Ukrainian index doesn't look good. Does it work for Cyrillic alphabet?

![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/26d94abd-32e2-4ca4-898f-144823268d46)

2024-05-21 06:24 UTC, qwrtln approved these changes
Perfect

2024-05-21 20:56 UTC, merged