[ES] Quote
Heegu-sama/Homm3BG pull request #473
Opened 2024-05-14 07:11 UTC by luischos

![es-37](https://github.com/Heegu-sama/Homm3BG/assets/45820491/42e82a91-0d35-49a0-8e4d-f8c9afc415cf)

2024-05-14 07:22 UTC, qwrtln commented
Please replace tabs with spaces, as the linter suggests.

2024-05-14 11:47 UTC, qwrtln approved these changes

2024-05-14 11:48 UTC, qwrtln requested changes
Fix linters

2024-05-14 11:50 UTC, qwrtln approved these changes

2024-05-14 11:59 UTC, qwrtln requested changes
checking

2024-05-14 12:00 UTC, qwrtln approved these changes

2024-05-15 15:05 UTC, qwrtln requested changes
Sorry, testing new mechanism for PR reviews. Please address the issues. This one if for real 😆

2024-05-15 20:16 UTC, qwrtln commented on main_es.tex
> +    Aunque se ha puesto mucho empeño en complacer a los fans, sobre todo en lo que se refiere al aspecto visual, la jugabilidad no hace más que estorbar.
```suggestion
  \textit{Aunque se ha puesto mucho empeño en complacer a los fans, sobre todo en lo que se refiere al aspecto visual, la jugabilidad no hace más que estorbar.
```
I suggest a slight change like so.

2024-05-16 06:23 UTC, luischos commented on main_es.tex
> +
What is the problem? I see this:
![1](https://github.com/Heegu-sama/Homm3BG/assets/45820491/b69e6ec3-de84-4905-8933-2686d30d3267)

2024-05-16 06:25 UTC, luischos commented
Anything else to fix @qwrtln ?

2024-05-16 07:22 UTC, qwrtln commented on main_es.tex
> +
```suggestion
```
Then it's not necessary.

2024-05-16 11:02 UTC, qwrtln approved these changes

2024-05-16 11:03 UTC, merged