ru/scenario_end
Heegu-sama/Homm3BG pull request #598
Opened 2024-06-19 12:48 UTC by ohgodnotagain

![ru-4](https://github.com/Heegu-sama/Homm3BG/assets/47557135/0f36b232-496c-46ee-866a-30493263a754)

2024-06-20 02:05 UTC, DarthGandalf requested changes

2024-06-20 02:05 UTC, DarthGandalf commented on translations/scenario_end.tex/ru.po
> +"Другие специфичные правила могут изменять преимущество от сбора кубиков фракции.\n"
```suggestion
"Другие специфичные для сценария правила могут изменять результат сбора чужих кубиков фракций.\n"
```

2024-06-20 02:05 UTC, DarthGandalf commented on translations/scenario_end.tex/ru.po
> +"В \\textbf{столкновениях (Clash)} с тремя и более игроками при получении \\textbf{кубика фракции} от каждого из соперников мгновенно приносит вам победу.\n"
кто приносит победу при этом получении?)

текст несвязный

2024-06-20 02:05 UTC, DarthGandalf commented on translations/scenario_end.tex/ru.po
> +"Пропустите шаги 11-13 подготовки к сценарию в кампании.\n"
```suggestion
"Пропустите шаги 11-13 подготовки к следующему сценарию в кампании.\n"
```

2024-06-20 02:05 UTC, DarthGandalf commented on translations/scenario_end.tex/ru.po
> +"Пропустите шаги 11-13 подготовки к сценарию в кампании.\n"
в прошлом разделе слово кампания было с большой. Должно быть с большой или маленькой?

2024-06-25 04:40 UTC, ohgodnotagain commented on translations/scenario_end.tex/ru.po
> +"В \\textbf{столкновениях (Clash)} с тремя и более игроками при получении \\textbf{кубика фракции} от каждого из соперников мгновенно приносит вам победу.\n"
переделал

2024-06-25 04:40 UTC, ohgodnotagain commented on translations/scenario_end.tex/ru.po
> +"Пропустите шаги 11-13 подготовки к сценарию в кампании.\n"
с большой, исправил

2024-06-25 10:32 UTC, DarthGandalf approved these changes

2024-06-25 13:57 UTC, merged