Ru/expansion content
Heegu-sama/Homm3BG pull request #618
Opened 2024-06-25 18:32 UTC by ohgodnotagain

![ru-4](https://github.com/Heegu-sama/Homm3BG/assets/47557135/6b7a3c10-bc8f-4f95-acc2-81eecfca6b1a)
![ru-5](https://github.com/Heegu-sama/Homm3BG/assets/47557135/b5dc0f76-961e-4ba1-aea8-0e7724f0625c)

2024-06-26 00:37 UTC, DarthGandalf requested changes

2024-06-26 00:37 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"К заклинанию \\textbf{Волшебной стрелы} можно применить эффект любой из Школ.\n"
ты тут потерял главную мысль - 1. любой, но только одной за раз, 2. при следующем касте школу можно опять выбрать любую

2024-06-26 00:37 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"Заклинания с одним символом Школы являются \\textbf{базовыми}, с четырьмя одинаковыми — \\textbf{экспертными}. Примененить игровой эффект можно только для одного из этих типов за раз.\n"
чиво??

ну и опечатка в слове применить

2024-06-26 00:37 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"Карты событий\\index{Event Cards} используются в играх с двумя и более игроками.\n"
```suggestion
"Карты событий\\index{Event Cards} могут использоваться в играх с двумя и более игроками.\n"
```

2024-06-26 00:37 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"В начале каждого ресурсного раунда (кроме первого), наберите карту и прочтите после получения ресурсов.\n"
возьмите? вытяните?
куда набрать?

2024-06-26 00:37 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"\\subsection*{\\pagetarget{Empowered Statistic}{Усиленные} карты статистикиs}\\index{Empowered Statistic Card}\n"
```suggestion
"\\subsection*{\\pagetarget{Empowered Statistic}{Усиленные} карты статистики}\\index{Empowered Statistic Card}\n"
```

2024-06-26 00:37 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"Они имеют только один эффект, идентичный экспертному в обычной карте статистики, но не требует применения вашего \\includesvg[height=10px]{\\svgs/expert.svg}.\n"
```suggestion
"Они имеют только один эффект, идентичный экспертному в обычной карте статистики, но не требующий траты вашего \\includesvg[height=10px]{\\svgs/expert.svg}.\n"
```

2024-06-27 09:39 UTC, ohgodnotagain commented on translations/expansion_content.tex/ru.po
> +"В начале каждого ресурсного раунда (кроме первого), наберите карту и прочтите после получения ресурсов.\n"
игровые карты набирают

2024-06-27 09:41 UTC, ohgodnotagain commented on translations/expansion_content.tex/ru.po
> +"Они имеют только один эффект, идентичный экспертному в обычной карте статистики, но не требует применения вашего \\includesvg[height=10px]{\\svgs/expert.svg}.\n"
тогда уже использования

2024-06-28 19:13 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"В начале каждого ресурсного раунда (кроме первого), наберите карту и прочтите после получения ресурсов.\n"
если в руку набрать полную руку карт, то да

но в этом предложении рука (и размер руки) не участвуют

2024-06-28 19:17 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"Каждый раз при вызове \\textbf{Волшебной стрелы} вы можете применить к ней один эффект любой из Школ на выбор (один эффект за вызов).\n"
не совсем так

одну школу на выбор

но если несколько эффектов работают с одной и той же школой, то мне кажется, ничего не мешает применить все их вместе

2024-06-30 16:34 UTC, ohgodnotagain commented on translations/expansion_content.tex/ru.po
> +"В начале каждого ресурсного раунда (кроме первого), наберите карту и прочтите после получения ресурсов.\n"
обновил

2024-06-30 16:35 UTC, ohgodnotagain commented on translations/expansion_content.tex/ru.po
> +"Каждый раз при вызове \\textbf{Волшебной стрелы} вы можете применить к ней один эффект любой из Школ на выбор (один эффект за вызов).\n"
обновил

2024-07-02 12:05 UTC, DarthGandalf commented on translations/expansion_content.tex/ru.po
> +"Каждый раз при вызове \\textbf{Волшебной стрелы} вы можете применить к ней один эффект любой из Школ на выбор (одна школа за вызов).\n"
```suggestion
"Каждый раз при вызове \\textbf{Волшебной стрелы} вы должны выбрать для этого вызова одну из Школ и применить соответствующие эффекты.\n"
```

2024-07-02 19:58 UTC, DarthGandalf approved these changes

2024-07-02 20:13 UTC, merged