Ru/all map locations
Heegu-sama/Homm3BG pull request #622
Opened 2024-06-27 19:58 UTC by ohgodnotagain

![ru-04](https://github.com/Heegu-sama/Homm3BG/assets/47557135/1ad59cc8-8b1b-438e-9c7a-13c275cbd0f7)
![ru-05](https://github.com/Heegu-sama/Homm3BG/assets/47557135/3e2c4ca6-7c54-43d7-9237-c0db8d28c830)
![ru-06](https://github.com/Heegu-sama/Homm3BG/assets/47557135/a760a3c9-71f3-4b7f-b2c0-02d90d1580c9)
![ru-07](https://github.com/Heegu-sama/Homm3BG/assets/47557135/4801db34-a385-422e-9f9b-80eebb942a1b)
![ru-08](https://github.com/Heegu-sama/Homm3BG/assets/47557135/511692e5-3f4b-48b6-8083-6b9a2fbb944c)
![ru-09](https://github.com/Heegu-sama/Homm3BG/assets/47557135/4f04b18e-5fd3-41dd-a82e-a84cdee11517)
![ru-10](https://github.com/Heegu-sama/Homm3BG/assets/47557135/39a93e4f-6941-410c-bd97-22335c28fb09)

2024-06-27 21:46 UTC, ohgodnotagain commented on translations/all_map_locations.tex/ru.po
> +"    \\pagetarget{War Machine Factory}{\\textbf{Фабрика военной техники}}\\par\n"
все-таки пускай будут боевые машины
вижу что в русскоязычных локализациях игры есть и то, и то - боевые машины как-то более вписывается

2024-06-28 19:45 UTC, DarthGandalf requested changes

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"      Бросьте \\pagetarget{Treasure Die}{кубик сокровищ}\\index{Treasure Die}\\index{Dice} и получите выпавший бонус (\\includesvg[height=10px]{\\svgs/resource_die.svg}, \\includesvg[height=10px]{\\
```suggestion
"      Бросьте \\pagetarget{Treasure Die}{кубик сокровищ}\\index{Treasure Die}\\index{Dice} и получите выпавший бонус (\\includesvg[height=10px]{\\svgs/resource_die.svg}, \\includesvg[height=10px]{\\svgs/2_treasure_die.svg}, \\includesvg[height=10px]{\\svgs/experience.svg} или \\includesvg[height=10px]{\\svgs/artifact.svg}).\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"    Немедленно получите изображённые ресурсы.\n"
```suggestion
"    Немедленно получите указанные ресурсы.\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"    Увеличьте добычу изображённых ресурсов.\n"
```suggestion
"    Увеличьте добычу указанных ресурсов.\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"    Выполните {\\LARGE\\textbf{x}} действие дважды.\n"
```suggestion
"    Выполните действие {\\LARGE\\textbf{x}} дважды.\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"Захват города может послужить \\pagelink{End}{выбыванием игрока}; сценарии обычно имеют специальные награды за захват.\n"
```suggestion
"Захват города может привести к \\pagelink{End}{выбыванию игрока}; сценарии обычно имеют специальные награды за захват.\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"\\textbf{Посёлки}\\index{Settlement} служат точкой появления вторичного героя и как место для перемещения основного героя при поражении.\n"
```suggestion
"\\textbf{Посёлки}\\index{Settlement} служат точкой появления вторичного героя и точкой, куда переместить основного героя при его поражении.\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"При захвате посёлка увеличьте на выбор \\includesvg[height=10px]{\\svgs/gold.svg}, \\includesvg[height=10px]{\\svgs/building_materials.svg} или \\includesvg[height=10px]{\\svgs/valuablegreater.svg}
```suggestion
"При захвате посёлка увеличьте на выбор добычу \\includesvg[height=10px]{\\svgs/gold.svg}, \\includesvg[height=10px]{\\svgs/building_materials.svg} или \\includesvg[height=10px]{\\svgs/valuablegreater.svg} на один шаг.\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"      \\textbf{Выполните одно из действий}: удалите карту способностей из руки, изучите верхнюю карту колоды способностей и возьмите ее в руку или поместите её в сброс колоды способностей.}\n"
```suggestion
"      \\textbf{Выполните одно из действий}: удалите карту способностей из руки, ЛИБО изучите верхнюю карту колоды способностей и поместите её в руку или в сброс колоды способностей.}\n"
```

2024-06-28 19:45 UTC, DarthGandalf commented on translations/all_map_locations.tex/ru.po
> +"  \\includesvg[height=10px]{\\svgs/bronze.svg} отряд выбирается игроком, контролирующим оборонительные отряды в ходе этого сражения.\n"
```suggestion
"  Отряд \\includesvg[height=10px]{\\svgs/bronze.svg} выбирается игроком, контролирующим оборонительные отряды в ходе этого сражения.\n"
```

2024-06-29 07:03 UTC, qwrtln commented
Будь осторожен с `\phatnom`. Иногда картинки не на одинаковом уровне. На английском у библиотеки хвостик (librar**y**), а на русском нет.
![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/ae8c500b-bec1-4c2a-a382-e102e763ec58)

2024-07-02 12:34 UTC, DarthGandalf approved these changes

2024-07-02 20:33 UTC, merged