Ru/fix index
Heegu-sama/Homm3BG pull request #646
Opened 2024-07-25 18:17 UTC by ohgodnotagain

![ru-53](https://github.com/user-attachments/assets/2af7e6e5-dd26-457b-a14a-59e0ac97d620)

2024-07-25 18:47 UTC, DarthGandalf requested changes

2024-07-25 18:47 UTC, DarthGandalf commented on latexmkrc
> +if ($ENV{TRANSLATED_AUTHOR}) {
А зачем оно здесь? Зачем может понадобиться включать/выключать перевод автора?

2024-07-25 18:47 UTC, DarthGandalf commented on translations/combat.tex/ru.po
> +"\\textbf{Препятствия}\\index{Препятствия} — любая карта на доске сражений считается препятствием.\n"
```suggestion
"\\textbf{Препятствия}\\index{Препятствия в битве} — любая карта на доске сражений считается препятствием.\n"
```

2024-07-25 18:49 UTC, DarthGandalf commented
Мне не нравятся эти карты, карты, карты, карты.

Что бы ни искать, надо в результате искать это и по имени, и по слову «карты». В английском слово Card стоит после, там такой проблемы нет

2024-07-25 19:37 UTC, ohgodnotagain commented on latexmkrc
> +if ($ENV{TRANSLATED_AUTHOR}) {
в metadata там стоит iftoggle - а он в свою очередь устанавливается в build.sh, исходя из того, какой язык выбран - сейчас для русского только, но может еще кому надо будет

2024-08-01 10:02 UTC, DarthGandalf commented on latexmkrc
> +if ($ENV{TRANSLATED_AUTHOR}) {
https://ru.wikipedia.org/wiki/YAGNI

2024-08-01 10:34 UTC, DarthGandalf commented
Смысл индекса — найти по термину что оно такое

Например, я пытаюсь понять, что такое мораль, но морали в указателе нет, есть только Положительная (П), Отрицательная (О) мораль и есть Действия морали (Д). Как мне предлагаешь найти эту мораль?)

В английском оно таки на букву М и легко находится

Аналогично, мне кажется, астрологов лучше сунуть на букву А, а не П, хотя можно и туда, и туда

Про ИИ будут искать наверно, на букву И, а не К?

Непонятно, в чём смысл «уникальных способностей» на У, и кто вообще по такому слову будет искать

Это был фидбек в целом; есть пара комментов по мелочи: усиленные статы, а не усиление? Штраф - штраф в битве? специальность - специальность героя? стрелки - стрелковые отряды?

2024-08-20 20:18 UTC, qwrtln commented on README.md
> +            <td align="center">—</td>
```suggestion
            <td align="center">0%</td>
```
Это графики

2024-08-20 22:12 UTC, DarthGandalf commented on README.md
> +            <td align="center">—</td>
графики в  смысле картинки?

2024-09-04 10:32 UTC, DarthGandalf approved these changes

2024-09-04 15:53 UTC, qwrtln commented on README.md
> +            <td align="center">0</td>
```suggestion
            <td align="center">0%</td>
```

2024-09-04 15:53 UTC, qwrtln approved these changes

2024-09-04 16:29 UTC, DarthGandalf commented on metadata.tex
> +\newtoggle{translatedauthor}
```suggestion
```

shouldn't be added anymore

2024-09-04 16:40 UTC, merged