[HE] difficulty
Heegu-sama/Homm3BG pull request #686
Opened 2024-09-18 14:06 UTC by davidpodless

Hi, long time no see....

![he-39](https://github.com/user-attachments/assets/0064f588-9b45-455c-994e-7a3859131ed8)
![he-40](https://github.com/user-attachments/assets/1d1b818c-d319-4b52-a044-a05ca28a193b)

2024-09-18 14:52 UTC, qwrtln requested changes
Please adjust the table cell heights. You can clearly see that the last one is too high, and the one before is too short.

2024-09-18 15:04 UTC, davidpodless commented
> Please adjust the table cell heights. You can clearly see that the last one is too high, and the one before is too short.

How do I do it?

2024-09-24 14:31 UTC, davidpodless commented
what do you think?

![he-39](https://github.com/user-attachments/assets/5ffe4361-5e33-4a84-afdb-a92fbd0618d4)
![he-40](https://github.com/user-attachments/assets/f7c41a58-2498-40d4-aaac-4dfc40e73941)

2024-09-24 15:13 UTC, qwrtln approved these changes

2024-09-24 15:17 UTC, qwrtln commented on translations/difficulty.tex/he.po
> +"{\\texthebrew{קלפי אסטרולוגיה נשלפים גם בתחילת סבב משאבים .}} \\\\ "
```suggestion
"{\\texthebrew{קלפי אסטרולוגיה נשלפים גם בתחילת סבב משאבים.}} \\\\ "
```

2024-09-24 15:29 UTC, merged